number1 = int(input('Number1 для додавання: '))
number2 = int(input('Number2 для додавання: '))
number3 = int(input('Number3 для множення: '))
number4 = int(input('Number4 для множення: '))
number5 = int(input('Number5 для ділення: '))
number6 = int(input('Number6 для ділення: '))
number7 = int(input('Number6 для віднімання: '))
number8 = int(input('Number6 для віднімання: '))
print(number1 + number2, number3 * number4, number5 / number6, number7 / number8)